[Sun Dec 07 13:58:41.523028 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856] mod_wsgi (pid=3855): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Sun Dec 07 13:58:41.523121 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856] Traceback (most recent call last):
[Sun Dec 07 13:58:41.523148 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Sun Dec 07 13:58:41.523280 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]     self.load_middleware()
[Sun Dec 07 13:58:41.523295 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Sun Dec 07 13:58:41.523449 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sun Dec 07 13:58:41.523464 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Sun Dec 07 13:58:41.523573 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]     self._setup(name)
[Sun Dec 07 13:58:41.523587 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Sun Dec 07 13:58:41.523609 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]     self._wrapped = Settings(settings_module)
[Sun Dec 07 13:58:41.523621 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
[Sun Dec 07 13:58:41.523641 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Dec 07 13:58:41.523653 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]   File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
[Sun Dec 07 13:58:41.523713 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]     __import__(name)
[Sun Dec 07 13:58:41.523755 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]   File "/var/www/PageLoadStatsPy/PageLoadStatsPy/settings.py", line 9
[Sun Dec 07 13:58:41.523765 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]     <<<<<<< HEAD
[Sun Dec 07 13:58:41.523772 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856]      ^
[Sun Dec 07 13:58:41.523780 2014] [:error] [pid 3855:tid 140647776909056] [client 10.71.247.104:57856] SyntaxError: invalid syntax
[Sun Dec 07 13:59:57.983820 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893] mod_wsgi (pid=5344): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Sun Dec 07 13:59:57.983925 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893] Traceback (most recent call last):
[Sun Dec 07 13:59:57.983964 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Sun Dec 07 13:59:57.984111 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]     self.load_middleware()
[Sun Dec 07 13:59:57.984128 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 44, in load_middleware
[Sun Dec 07 13:59:57.984329 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Sun Dec 07 13:59:57.984346 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 54, in __getattr__
[Sun Dec 07 13:59:57.984480 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]     self._setup(name)
[Sun Dec 07 13:59:57.984497 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 49, in _setup
[Sun Dec 07 13:59:57.984521 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]     self._wrapped = Settings(settings_module)
[Sun Dec 07 13:59:57.984535 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 128, in __init__
[Sun Dec 07 13:59:57.984556 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Sun Dec 07 13:59:57.984570 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]   File "/usr/lib/python2.7/dist-packages/django/utils/importlib.py", line 40, in import_module
[Sun Dec 07 13:59:57.984640 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]     __import__(name)
[Sun Dec 07 13:59:57.984695 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]   File "/var/www/PageLoadStatsPy/PageLoadStatsPy/settings.py", line 9
[Sun Dec 07 13:59:57.984705 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]     <<<<<<< HEAD
[Sun Dec 07 13:59:57.984714 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893]      ^
[Sun Dec 07 13:59:57.984723 2014] [:error] [pid 5344:tid 140290132162304] [client 10.71.247.104:57893] SyntaxError: invalid syntax
[Mon Dec 15 02:05:15.149177 2014] [:error] [pid 28840:tid 140181172590336] [client 10.201.16.27:52304] mod_wsgi (pid=28840): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Mon Dec 15 02:05:15.154436 2014] [:error] [pid 28840:tid 140181172590336] [client 10.201.16.27:52304] IOError: failed to write data
[Tue Dec 16 02:05:17.292251 2014] [:error] [pid 1682:tid 140118929168128] [client 10.201.16.27:44190] mod_wsgi (pid=1682): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Tue Dec 16 02:05:17.296264 2014] [:error] [pid 1682:tid 140118929168128] [client 10.201.16.27:44190] IOError: failed to write data
[Sun Dec 21 02:05:17.154442 2014] [:error] [pid 1724:tid 140247341930240] [client 10.201.16.27:44865] mod_wsgi (pid=1724): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Sun Dec 21 02:05:17.158730 2014] [:error] [pid 1724:tid 140247341930240] [client 10.201.16.27:44865] IOError: failed to write data
[Wed Dec 24 02:05:15.374947 2014] [:error] [pid 1690:tid 139927509477120] [client 10.201.16.27:34776] mod_wsgi (pid=1690): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Wed Dec 24 02:05:15.379760 2014] [:error] [pid 1690:tid 139927509477120] [client 10.201.16.27:34776] IOError: failed to write data
[Thu Dec 25 02:05:15.341473 2014] [:error] [pid 1714:tid 140017057879808] [client 10.201.16.27:47974] mod_wsgi (pid=1714): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Thu Dec 25 02:05:15.347526 2014] [:error] [pid 1714:tid 140017057879808] [client 10.201.16.27:47974] IOError: failed to write data
[Fri Dec 26 02:05:17.076540 2014] [:error] [pid 1752:tid 140343768975104] [client 10.201.16.27:36768] mod_wsgi (pid=1752): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Fri Dec 26 02:05:17.081704 2014] [:error] [pid 1752:tid 140343768975104] [client 10.201.16.27:36768] IOError: failed to write data
[Sat Dec 27 02:05:16.071082 2014] [:error] [pid 1692:tid 139652270880512] [client 10.201.16.27:50321] mod_wsgi (pid=1692): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Sat Dec 27 02:05:16.077126 2014] [:error] [pid 1692:tid 139652270880512] [client 10.201.16.27:50321] IOError: failed to write data
[Mon Dec 29 02:05:17.358514 2014] [:error] [pid 1747:tid 140203075290880] [client 10.201.16.27:44046] mod_wsgi (pid=1747): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Mon Dec 29 02:05:17.363935 2014] [:error] [pid 1747:tid 140203075290880] [client 10.201.16.27:44046] IOError: failed to write data
[Fri Jan 02 02:05:15.582400 2015] [:error] [pid 1728:tid 140359799600896] [client 10.201.16.27:55471] mod_wsgi (pid=1728): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Fri Jan 02 02:05:15.586893 2015] [:error] [pid 1728:tid 140359799600896] [client 10.201.16.27:55471] IOError: failed to write data
[Sat Jan 03 02:05:17.921702 2015] [:error] [pid 1726:tid 140584060671744] [client 10.201.16.27:36933] mod_wsgi (pid=1726): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Sat Jan 03 02:05:17.927822 2015] [:error] [pid 1726:tid 140584060671744] [client 10.201.16.27:36933] IOError: failed to write data
[Sun Jan 04 02:05:15.927756 2015] [:error] [pid 1699:tid 139957154842368] [client 10.201.16.27:48083] mod_wsgi (pid=1699): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Sun Jan 04 02:05:15.931506 2015] [:error] [pid 1699:tid 139957154842368] [client 10.201.16.27:48083] IOError: failed to write data
[Mon Jan 05 02:05:17.185513 2015] [:error] [pid 10363:tid 140424433862400] [client 10.201.16.27:49165] mod_wsgi (pid=10363): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Mon Jan 05 02:05:17.189585 2015] [:error] [pid 10363:tid 140424433862400] [client 10.201.16.27:49165] IOError: failed to write data
[Tue Jan 06 02:05:15.727491 2015] [:error] [pid 1696:tid 140341520844544] [client 10.201.16.27:60007] mod_wsgi (pid=1696): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Tue Jan 06 02:05:15.731585 2015] [:error] [pid 1696:tid 140341520844544] [client 10.201.16.27:60007] IOError: failed to write data
[Thu Jan 08 02:05:15.315623 2015] [:error] [pid 1730:tid 140230816429824] [client 10.201.16.27:48877] mod_wsgi (pid=1730): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Thu Jan 08 02:05:15.321985 2015] [:error] [pid 1730:tid 140230816429824] [client 10.201.16.27:48877] IOError: failed to write data
[Thu Jan 08 09:21:26.365223 2015] [:error] [pid 1702:tid 140488740873984] [client 10.201.17.30:64828] mod_wsgi (pid=1702): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'., referer: http://giftsqa.proflowers.com/pls/chart/?target_id=102
[Thu Jan 08 09:21:26.370011 2015] [:error] [pid 1702:tid 140488740873984] [client 10.201.17.30:64828] IOError: failed to write data, referer: http://giftsqa.proflowers.com/pls/chart/?target_id=102
[Fri Jan 09 02:05:16.633214 2015] [:error] [pid 1697:tid 140320423515904] [client 10.201.16.27:50691] mod_wsgi (pid=1697): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Fri Jan 09 02:05:16.638379 2015] [:error] [pid 1697:tid 140320423515904] [client 10.201.16.27:50691] IOError: failed to write data
[Sat Jan 10 02:05:14.595060 2015] [:error] [pid 1692:tid 140581074310912] [client 10.201.16.27:41515] mod_wsgi (pid=1692): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Sat Jan 10 02:05:14.598786 2015] [:error] [pid 1692:tid 140581074310912] [client 10.201.16.27:41515] IOError: failed to write data
[Sun Jan 11 02:05:16.645665 2015] [:error] [pid 1692:tid 140175493482240] [client 10.201.16.27:45566] mod_wsgi (pid=1692): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Sun Jan 11 02:05:16.652753 2015] [:error] [pid 1692:tid 140175493482240] [client 10.201.16.27:45566] IOError: failed to write data
[Mon Jan 12 02:05:16.662709 2015] [:error] [pid 18207:tid 140706031048448] [client 10.201.16.27:52365] mod_wsgi (pid=18207): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Mon Jan 12 02:05:16.680379 2015] [:error] [pid 18207:tid 140706031048448] [client 10.201.16.27:52365] IOError: failed to write data
[Tue Jan 13 02:05:17.207518 2015] [:error] [pid 13771:tid 139694247458560] [client 10.201.16.27:56044] mod_wsgi (pid=13771): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Tue Jan 13 02:05:17.214164 2015] [:error] [pid 13771:tid 139694247458560] [client 10.201.16.27:56044] IOError: failed to write data
[Tue Jan 13 09:25:18.882586 2015] [:error] [pid 28352:tid 139957708465920] [client 10.201.16.27:57639] mod_wsgi (pid=28352): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Tue Jan 13 09:25:18.887029 2015] [:error] [pid 28352:tid 139957708465920] [client 10.201.16.27:57639] IOError: failed to write data
[Tue Jan 13 09:35:19.411316 2015] [:error] [pid 5153:tid 140128471320320] [client 10.201.16.27:35380] mod_wsgi (pid=5153): Exception occurred processing WSGI script '/var/www/PageLoadStatsPy/pageloadstats.wsgi'.
[Tue Jan 13 09:35:19.411366 2015] [:error] [pid 5153:tid 140128471320320] [client 10.201.16.27:35380] IOError: failed to write data
